FROM ubuntu:22.04

COPY simple /simple

COPY zombie /usr/bin/zombie

COPY sigterm_handler /usr/bin/sigterm_handler

COPY sigterm_loop /usr/bin/sigterm_loop

COPY dumb_shell /usr/bin/dumb_shell

CMD ["/simple"]
