[package]
name = "pid1"
version = "0.1.0"
edition = "2021"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.27.1", features = ["process", "signal"] }
signal-hook = "0.3.17"
thiserror = "1"
